### ISSUE TITLE
Headers doubled

### ISSUE THREAD

**Issue by bungle** [openresty/lua-resty-upload#17]
I get headers like this:

``` 
["Content-Disposition","form-data; name=\"nick\"","Content-Disposition: form-data; name=\"nick\""]
```

While original request only had this:
`Content-Disposition: form-data; name="nick"``

It seems all the headers this returns are doubled? Is that what is expected?

**Comment by agentzh** [comment]
@bungle Nope, it does not look like something expected. Mind to craft a minimal test case (and even a patch)? ;) Thanks!

**Comment by bungle** [comment]
I think there is first this parsed stuff in r[1] and r[2] and the rawstuff in r[3]. I don't think it needs to have that r[3]. I will check it and write a patch.

**Comment by agentzh** [comment]
@bungle Okay, I now remember there is a requirement to have the raw header in the 3rd element. So it's the expected behaviour.

**Comment by bungle** [comment]
Ok, I consider this closed then. Good to know, though.
