### ISSUE TITLE
MAX_LINE_SIZE, 512 is too small in Korean

### ISSUE THREAD

**Issue by sjnam** [openresty/lua-resty-upload#19]
One Korean character is 3-byte in UTF-8. And MS Windows limits a single path to 260 characters.
Therefore maximum Korean caharacter path or filename length is about 780 bytes in UTF-8.

local MAX_LINE_SIZE = 512

MAX_LINE_SIZE, 512 is too small to contain max Korean character filename.

How about increase the size MAX_LINE_SIZE to 1024?

Thank you.

**Comment by bungle** [comment]
Windows doesn't limit 260 chars path. It is only that some old Windows APIs do that. NTFS supports 32k characters paths.

**Comment by agentzh** [comment]
@sjnam Yes, we can change the default. Or better, make this configurable by the caller. Patches welcome :)
