### ISSUE TITLE
use upload but nginx is block

### ISSUE THREAD

**Issue by 5977862** [openresty/lua-resty-upload#21]
I use lua restry upload, and ngx.req.read_body() , I put those in /opt/xx.lua;

nginx conf as below ~
access_by_lua_file /opt/xx.lua
proxy_pass http://localhosy:9000

the proxy pass is my django project ,it works ,and I try to change another url~ 

I can process .lua in get and post(without file,use formdata is ok~) method,but when I post file ,the nginx alway raise error~

"
[error] 25390#0: *442 upstream prematurely closed connection while reading response header from upstream, client: 192.168.10.26, server: localhost, request: "POST /app/get_all_args/ HTTP/1.1", upstream: "http://127.0.0.1:8090/app/get_all_args/", host: "192.168.10.27"
"
IP 192.168.10.26 is my client
IP 192.168.10.27 is my nginx
URL 127.0.0.1:8090/app/get_all_args/ is my project,which is proxied to after lua accept~

client always block,and I try use ngx.say ~ It seems everything is ok~ 
So I don't know what's the problem is ~

In .lua when auth is ok , I use ngx.exit(ngx.OK) ngx.HTTP_OK is bad ~
when auth filed, I used ngx.say("xxx") then return
Now I am sure I use ngx.exit(ngx.OK)

So please help me~  Thank you ~

Sorry for my poor English~ I can desc it in Chinese~ = =!

**Comment by agentzh** [comment]
@5977862 Because you are using lua-resty-upload to read the request body so the ngx_proxy module can no longer have any request body successfully read. If that's what you want, then you can just use `ngx.req.set_header("Content-Length", 0)` in your `access_by_lua*` handler to avoid ngx_proxy trying to read the request body that no longer exists.

If you prefer Chinese, please join the openresty (Chinese) mailing list for discussions:

https://openresty.org/#Community

**Comment by 5977862** [comment]
I set ngx.req.set_header("Content-Length", 0), It works~

But I need all data from client,Lua just read data process auth~ then all data send to proxy_pass ,So what should I do?

**Comment by agentzh** [comment]
@5977862 Then you should use the Lua API functions `ngx.req.init_body`, `ngx.req.append_body`, and `ngx.req.finish_body` to reconstruct the buffered request body stored inside the nginx core for other nginx modules like ngx_lua.

**Comment by agentzh** [comment]
@5977862 Alas. Apparently it's much more efficient if you migrate all your web app over to ngx_lua.

**Comment by 5977862** [comment]
Is there any way make raw nginx request proxy to my server by lua ~ I had try set_body ~

But still hope use nginx raw data~

**Comment by agentzh** [comment]
@5977862 Via cosockets, yes. Or using existing lua libraries based on cosockets (like some version of lua-resty-http).

**Comment by agentzh** [comment]
Because this "blocking" issue is really a false positive. I'm closing this ticket. Further discussions should go to the openresty-en (English) mailing list or the openresty (Chinese) mailing list instead. See https://openresty.org/#Community Thanks for your cooperation.
