### ISSUE TITLE
Problem with big file upload: Request Entity too large

### ISSUE THREAD

**Issue by mango009** [openresty/lua-resty-upload#27]
I'm trying to upload a slightly big file of size ~3MB. And I'm getting a 413 error. The nginx error is:

2016/08/24 21:35:05 [error] 50785#0: *2 client intended to send too large body: 3520276 bytes, client: 127.0.0.1, server: localhost, request: "POST /test HTTP/1.1", host: "localhost:8070". 

And my client side error:
<html>
<head><title>413 Request Entity Too Large</title></head>
<body bgcolor="white">
<center><h1>413 Request Entity Too Large</h1></center>
<hr><center>openresty/1.9.15.1</center>
</body>
</html>

Is there any configuration I need to do on the Nginx side?

**Comment by agentzh** [comment]
@mango009 See http://nginx.org/en/docs/http/ngx_http_core_module.html#client_max_body_size

**Comment by mango009** [comment]
Thank you!
