### ISSUE TITLE
Is it necessary that have boundary in a post request？

### ISSUE THREAD

**Issue by mylq** [openresty/lua-resty-upload#28]
@agentzh Does lua-resty upload module support  curl's post request ?
There is one problem I got , I tried to use this command : curl -d 'payload' -X POST 'http://localhost/uploadfile?path=/data/test.txt    to post data to server,but failed. The error log is posted below 

2016/08/31 18:38:56 [error] 48977#0: *77 [lua] savefile.lua:5: the raw header is POST /uploadfile?path=/data/ds HTTP/1.1^M
User-Agent: curl/7.35.0^M
Host: localhost^M
Accept: */*^M
Content-Length: 8^M
Content-Type: application/x-www-form-urlencoded^M
^M
, client: 127.0.0.1, server: localhost, request: "POST /uploadfile?path=/data/test.txt HTTP/1.1", host: "localhost"
2016/08/31 18:38:56 [error] 48977#0: *77 [lua] savefile.lua:11: failed to new upload: no boundary defined in Content-Type, client: 127.0.0.1, server: localhost, request: "POST /uploadfile?path=/data/test.txt HTTP/1.1", host: "localhost"

The Content-Type don't have boundary so the upload is failed. Is there any solution to solve this problem ?

**Comment by bungle** [comment]
As you can see, you are using `application/x-www-form-urlencoded`. This is different than `multipart/form-data` for which `lua-resty-upload` is for.

Check out these:

https://github.com/openresty/lua-nginx-module#ngxreqread_body
https://github.com/openresty/lua-nginx-module#ngxreqget_body_data
https://github.com/openresty/lua-nginx-module#ngxreqget_body_file

**Comment by agentzh** [comment]
And also this:

https://github.com/openresty/lua-nginx-module/#ngxreqget_post_args

:)

**Comment by mylq** [comment]
Thanks
