### ISSUE TITLE
Request header is repeated

### ISSUE THREAD

**Issue by 362228416** [openresty/lua-resty-upload#34]
``
read: ["header",["Content-Disposition","form-data; name=\"file1\"; filename=\"a.txt\"","Content-Disposition: form-data; name=\"file1\"; filename=\"a.txt\""]]
read: ["header",["Content-Type","text\/plain","Content-Type: text\/plain"]]
read: ["body","Hello"]
read: ["body",", wor"]
read: ["body","ld"]
read: ["part_end"]
read: ["header",["Content-Disposition","form-data; name=\"test\"","Content-Disposition: form-data; name=\"test\""]]
read: ["body","value"]
read: ["body","\r\n"]
read: ["part_end"]
read: ["eof"]
read: ["eof"]
```

Each request header content in pairs，

**Comment by agentzh** [comment]
Multi-part means there an be multiple "parts" each of which has its own header.

**Comment by bungle** [comment]
@362228416, see also #17
