### ISSUE TITLE
oh,i want say something,openresty always have problem in upload image file 

### ISSUE THREAD

**Issue by rhettli** [openresty/lua-resty-upload#36]
**Are there anyone upload image file in trouble?
The picture which be  upload to server ,it can't be open as image file , just like this:**

## The nomal pic:

![123](https://user-images.githubusercontent.com/26317003/28716619-ce48a0de-73d0-11e7-944e-34a0fa7c6c7d.jpg)

## And this is upload to server :

![123](https://user-images.githubusercontent.com/26317003/28716660-fc44bee6-73d0-11e7-8bc2-b169525cf662.jpg)

PS:I am chinese ,maybe i  write many wrong  world ,just ingroe it,just recognize my meaning

**Comment by agentzh** [comment]
@rhettli We have many production users doing large column of uploads with OpenResty. So I believe it's just mistakes in your own code. If you believe it's a bug in OpenResty, please provide a *minimal* and *standalone* example that we can easily run and reproduce the issue on our side. Otherwise we cannot help you with so little info since we are not gods. BTW, you can always join the openresty (Chinese) mailing list for discussions if you prefer Chinese: http://openresty.org/en/community.html

**Comment by rhettli** [comment]
maby many people use linux os to dev their project, I use windows xp to develop my project ,so the openresty of window have a problem(bug) that less people find it .i stick my config of nginx and upload code of lua here . please make sure if the openresty of windows have this bug which cause upload file to server can't be open. @agentzh 

**here is nginx config:**
```
pid tmp/nginx.pid;

worker_processes 1;

events {
    worker_connections 4096;
}

http {
    sendfile on;
    include mime.types;
	#default_type  application/octet-stream;
	
    # lor initialization
    lua_package_path "app/?.lua;./?.lua;;";					#;/usr/local/lor/?.lua
    #lua_code_cache on;

    server {
        listen 8081;
        set $template_root '';
	# 加载静态文件，匹配到就不会往后匹配了。
    location  ~  /static {
        #alias app/views/static; #app/views/static;
        root  app/views;
    }
    location ~ /upload_ {#这里配置上传脚本路由。
        content_by_lua_file app/upload.lua;
    }
 	#主目录路由接入
    location  ~  / {
     		lua_code_cache  off;	#仅仅在调试的时候关闭，正式环境需要打开。
            content_by_lua_file ./app/main.lua;
    }
    access_log logs/dev-access.log;
    error_log logs/dev-error.log;

    }
}

```

**and here is lua upload code(copy form net):**
```
local upload = require ("resty.upload")
local chunk_size = 4096  --如果不设置默认是4096.
local form = upload:new(chunk_size)
local file
local filelen=0
form:set_timeout(1000) -- 1 sec

local osfilepath = "app/views/static/"  --文件默认的保存位置


function get_filename(res)
    local fname = ngx.re.match(res,'(.+)filename="(.+)"(.*)')
    if fname then
        return fname[2]
    end
end

  local i=0
  while true do
      local typ, res, err = form:read()
      if not typ then
          ngx.say("failed to read: ", err)
          return
      end
      if typ == "header" then
          if res[1] ~= "Content-Type" then 
              local filename = get_filename(res[2])
              if filename then
                  i=i+1
                  local filepath = osfilepath  .. filename
                  file = io.open(filepath,"w+")
                  if not file then
                      ngx.say("failed to open file ")
                      return
                  end
              else
              end
          end
      elseif typ == "body" then
          if file then
              filelen= filelen + tonumber(string.len(res))    
              file:write(res)
          else
          end
      elseif typ == "part_end" then
          if file then
              file:close()
              file = nil
              ngx.say("file upload success")
          end
      elseif typ == "eof" then
          break
      else
      end
  end
  
  
  if i==0 then --0123456789
      ngx.say("please upload at least one file!")
      return
  end
--return middleware
```

**Comment by agentzh** [comment]
@rhettli On Windows you should open the file as a binary file otherwise it treats it as a text file and writes extra bytes to the file automatically. Basically you should pass the "b" flag to the `io.open()` call.

**Comment by rhettli** [comment]
@agentzh thx,thank for your. help,this problem make me confusing 'my project delay long time.

I love lua and openresty.
