### ISSUE TITLE
Does this support multiple upload?

### ISSUE THREAD

**Issue by weichangdong** [openresty/lua-resty-upload#38]
Does this support the upload of bulk files? If this does not support, Can you give me a reference plz?

**Comment by weichangdong** [comment]
the html code is 
```
<form action="http://127.0.0.1:2222/mulupload" method="post" enctype="multipart/form-data">
<input type="file" name="file1">
<input type="file" name="file2">
<input type="text" name="wcd" />
<br />
<input type="submit" name="submit" value="Submit" />
```

**Comment by weichangdong** [comment]
It should be possible, though I haven't done it yet, but I think it's going to be fast

**Comment by bungle** [comment]
yes it does.

**Comment by weichangdong** [comment]
3q.
Yes, I have succeeded. The reason for the problem was that the second file names were covered by the first file, which led to the fact that I could not upload them in bulk
