### ISSUE TITLE
Subrequest question

### ISSUE THREAD

**Issue by SWSAmor** [openresty/lua-resty-upload#40]
Thank you for your work, i use this module without any problems for a year. 
But now I tried to handle the upload with the same script, but from a subrequest, and i got this:
> attempt to read the request body in a subrequest
> stack traceback:
> coroutine 0:                                                                                                                                                  > [C]: in function 'req_socket'                                                                                                                         > /usr/lib/lua/luarocks/share/lua/5.1/resty/upload.lua:61: in function 'new'

i called the script with this:
> local res = ngx.location.capture("/upl_worker", {share_all_vars = true, always_forward_body=true})

Is it impossible, or i miss something?

**Comment by agentzh** [comment]
@SWSAmor The error message is self-explanatory, you cannot read a client request body inside a subrequest, this is a limitation in nginx core's subrequest design. You should only read the request body from a main request.
