### ISSUE TITLE
HTTPS upload?

### ISSUE THREAD

**Issue by sdmrnv** [openresty/lua-resty-upload#46]
This module works fine when I have upload via http. But when I used httpS it crashes on call upload:new(chunk_size) phase. Does exist method for working with httpS?

**Comment by agentzh** [comment]
@sdmrnv It is HTTP/2 that is not yet supported by this library. Just disable HTTP/2 and you should be good with HTTPS alone.

**Comment by sdmrnv** [comment]
@agentzh Thanks! It's work! But unfortunately now I can't divide requests to http_v1 (when used upload) and http_v2 (for non-upload requests).
